import streamlit as st
import json 
from streamlit_lottie import st_lottie 

st.header('Orthodontic Disease Finder')
st.write("Orthodontics is a dental specialty that focuses on aligning the bite and straightening teeth.")
st.write("---")
st.header('Treatment')
st.header("1.Teeth Crooked Teeth")
st.write("Braces - Braces are a type of an orthodontic appliance that consist of brackets, bands, and wires. They apply constant pressure on the jaw over an extended period, which makes it adapt to the pressure in a certain direction, causing it to move into the desired position. There are three types of braces available including metal braces, ceramic braces, and lingual braces. You can talk to your orthodontist and know what may be the most appropriate teeth alignment solution for you based on the results of your oral examination.")
st.write("Invisalign - Invisalign is basically invisible braces. The treatment includes clear or transparent trays that are custom-created to fit over your teeth set. Your orthodontist will create several molds, and you will have to move from one mold to another until your teeth finally move into the correct position. Adults often go for Invisalign since they are clear and can easily go unnoticed. However, it's the higher cost of Invisalign that makes braces a more practical solution. If your teeth are crookedn and you think that they can potentially lead to severe health issues or if you simply want a straighter and healthier smile, book an appointment with the experts at Putnam Orthodontics. Learn what is the best orthodontic treatment for you and take the first step to your best smile.")
st.write("---")
st.header("2.Teeth Crossbite")
st.write("Crossbite - Medical treatment is the only way to truly correct an underbite and align teeth correctly. At the very least, medical treatment can improve the appearance of an underbite.")
st.write("In less severe cases of underbite, a dentist may be able to use wire or plastic braces or other dental appliances to move the teeth into their correct place.")
st.write("Removal of one or more teeth on the lower jaw may also help improve the appearance of an underbite if overcrowding of the teeth is contributing to the issue. A dentist may also use a grinding device to shave down or smooth teeth that are large or stick out.")
st.write("In more severe cases of underbite, a dentist may recommend surgery to correct the condition.")
st.write("---")
st.header("3. Excessive Overjet")
st.write("If you have concerns about your teeth or smile, start by making an appointment with your dentist.")
st.write("They can examine your teeth and determine the right treatment for you. In many cases, a general dentist can do veneer, dental bonding, and crown procedures.")
st.write("They can also refer you to an orthodontist to discuss treatment options. An orthodontist specializes in jaw issues and teeth alignment and can install dental braces.")
st.write("You may need jaw corrective surgery for a severe overjet, in which case you’ll see an oral surgeon.")
st.write("This procedure can realign your jaw and teeth. Jaw corrective surgery ranges from $20,000 to $40,000. Your health insurance may cover the cost of this procedure if it’s medically necessary.")
st.write("---")
st.header("4.Overbite")
st.write("Growth modification devices, or palate expanders, used during growth spurts to re-position the jaw.")
st.write("Braces to slowly move all the teeth into correct alignment.")
st.write("Removal of baby teeth or permanent teeth to make room for adult teeth.")
st.write("Retainers to keep the teeth in alignment after braces.")
st.write("Clear braces to move only the teeth affected by the overbite. Surgery to correct jaw alignment.")
st.write("Teeth removal to allow the remaining teeth more room.")
st.write("---")
st.header("5.Space Between Teeth - Medical Treatment")
st.write("Treatment for a diastema may or may not be necessary depending on the underlying cause. For some people, a diastema is nothing more than a cosmetic issue and it doesn’t indicate a problem like gum disease.")
st.write("Braces are a common treatment for diastema. Braces have wires and brackets that put pressure on teeth and slowly move them together, which closes a gap. Invisible or removable braces may also fix some cases of diastema.")
st.write("If you don’t want braces, talk to your doctor about cosmetic procedures to fill gaps between your teeth. Veneers or bonding is another option. This procedure uses a tooth-colored composite which can either fill gaps or fit over teeth to improve the appearance of your smile. This procedure is also useful for fixing a cracked or chipped tooth. You may also be a candidate for a dental bridge, which can replace a missing tooth or correct a gap.")
st.write("If the gums above your two upper front teeth overextend and cause a gap, surgery to remove excess tissue can correct the gap. You may need braces to fully close larger gaps.")
st.write("If your doctor diagnoses you with gum disease, you must receive treatment to stop the infection before you seek treatment to close a gap. Treatment for gum disease varies, but may include scaling and root planing to remove hardened plaque (tartar) from above and below the gums. This eliminates the bacteria causing the disease.")
st.write("Severe gum disease may require surgery to remove tartar that has accumulated deep within the gums. Surgery can also involve bone and tissue regeneration.")
st.write("---")
st.header("6.Underbite")
st.write("Medical treatment is the only way to truly correct an underbite and align teeth correctly. At the very least, medical treatment can improve the appearance of an underbite.")
st.write(" In less severe cases of underbite, a dentist may be able to use wire or plastic braces or other dental appliances to move the teeth into their correct place.")
st.write("Removal of one or more teeth on the lower jaw may also help improve the appearance of an underbite if overcrowding of the teeth is contributing to the issue. A dentist may also use a grinding device to shave down or smooth teeth that are large or stick out.")
st.write("In more severe cases of underbite, a dentist may recommend surgery to correct the condition.")
st.write("---")